### ISSUE TITLE
X-Rocket-Nginx-Bypass + Connected user

### ISSUE THREAD

**Issue by manuhook** [SatelliteWP/rocket-nginx#47] opened 2017-02-24 10:13 UTC
Hi Maxime,

Today it's not possible to Bypass Wordpress when the user is logged because of the cookie.
If you find the cookie "wordpress_logged_in_" you set $rocket_bypass to 0.

With wp-rocket the cached files for a logged user ar inside a directory like : /wp-content/cache/wp-rocket/www.domain-Username-NUM-ID/

What if when a user is logged we add a function to create a cookie named Username-NUM-ID 
and with rocket-nginx we check if this cookie exist to get his name and allow the nginx redirect ?

Do you think it will be possible ?

Thank you

**Comment by maximejobin** [comment] 2017-02-24 15:15
I'm working on version 2.0 which is almost finished but as I'm not paid for this project, I only do it when I have free time... which does not happen really often.

That said, you will be able to control cookies, headers and so much more.  So what you are asking will be doable easily! :-)

**Comment by maximejobin** [comment] 2017-02-24 19:39
I totally misunderstood what you were saying.  Sorry about that.

I'm not sure what would be needed but I have to look into it.

**Comment by manuhook** [comment] 2017-07-06 11:25
Sorry for the late answer.

I was thinking to create a specific cookie when a user is logged
This cookie name will be : Username-NUM-ID

In order to match the name of the cached directory created by wp-rocket : /wp-content/cache/wp-rocket/www.domain-Username-NUM-ID/

With X-Rocket-Nginx the goal will be to detect if this cookies exist, and use his name in order to set rocket_end correctly

Thanks for your help :)

**Comment by maximejobin** [comment] 2018-08-31 18:43
For some reason, I never saw that answer. I would suggest that you send your code/request to WP Rocket. If they implement something like this in the official plugin, I would gladly consider doing what is needed to make it work with Rocket-Nginx.

**Comment by maximejobin** [comment] 2018-09-19 13:43
Maybe @Tabrisrp could help or give insights about what they think.

**Comment by Tabrisrp** [comment] 2018-09-19 14:19
The `Username-NUM-ID` identifier is already based on a cookie generated by WordPress, which name is `wordpress_logged_in_` + the value of the  `COOKIEHASH` constant

**Comment by maximejobin** [comment] 2018-09-19 16:02
The problem is that scripting with Nginx is really limited. You cannot get a substring the way you would do it in PHP.

I would need the exact key to be found somewhere "as-is".

Something like this:
Cookie name: wprocket-user-hashkey
value: maxime-0352fa113050320656c94

That way, the value of the cookie can be used to check if a file/folder exists.

**Comment by manuhook** [comment] 2018-09-20 07:30
Hi Maxime,

I've manage to make it work with my app, but my app need to send the wp logged username in the headers ( int he example bellow http_x_rest_username).

rocket-nginx.conf :
if ($http_x_rest_username != "") {
        set $rocket_end "/cache/wp-rocket/$http_host-$http_x_rest_username-MY_ROCKET_CACHE_SECRET_KEY/$request_uri/index$rocket_https_prefix.html$rocket_encryp$
}

I've also add this on WP-Rocket in order to create the cached file for the connected user if it doesn't exist and the app is sending the http_x_rest_username header : 

    $headerStringValue = $_SERVER;
    $username = $headerStringValue['HTTP_X_REST_USERNAME'];

    if ($username != "") {
        $user_key = $username . '-' . $rocket_secret_cache_key;
        $request_uri_path = $rocket_cache_path . $host . '-' . $user_key . rtrim( $request_uri, '/' );
    }else{
        $request_uri_path = $rocket_cache_path . $host . rtrim( $request_uri, '/' );
    }

**Comment by maximejobin** [comment] 2020-06-25 16:48
I'm closing this issue as it would almost be impossible to validate the user with Nginx. The authentication should be done by WordPress and the cache served by WP-Rocket. I understand the benefit of "skipping" WordPress and serving the cache file directly but there is no way of doing it directly with Rocket-Nginx in a configuration file.

**Closed by maximejobin** 2020-06-25 16:48 UTC
Labels: wontfix
