### ISSUE TITLE
Will not load files that have been gzip compressed, but load .html。

### ISSUE THREAD

**Issue by flipwalls** [SatelliteWP/rocket-nginx#155] opened 2021-04-10 10:37 UTC
Sorry, I do not speak English. I use Google Translate.
**file：rocket-nginx/rocket-nginx.tmpl
已生成的文件：default.conf**
Let's open lines 39 to 47，If the client supports br compression, it will not return files that have been gzip compressed，I think this should be changed
```php
# Is GZIP accepted by client ?
if ($http_accept_encoding ~ gzip) {
	set $rocket_encryption "_gzip";
}

# Is Brotli accepted by client ?
if ($http_accept_encoding ~ br) {
	set $rocket_encryption "_gzip";
}
```
The client supports br compression, so we still load files that have been gzip compressed and perform br compression again, but I don’t know if garbled characters will occur in this way. I hope that the next version will be updated. Someone has created a report that cannot load files that have been gzip compressed. I think this is the reason.
**I wish you a happy weekend.**
**The following is the Chinese version of this question**
nginx-rocket在客户端支持br压缩也就是accept-encoding头部包含br的时候不会加载已经gzip压缩过的文件，解决方案是已经生成的配置文件第39行到47行修改为上面那个代码。

**Comment by flipwalls** [comment] 2021-04-10 10:46
My website is https://www.xudu.org

**Comment by maximejobin** [comment] 2021-04-13 13:56
This is a duplicate of #134 

Thank you for reporting the issue.

**Closed by maximejobin** 2021-04-13 13:56 UTC
Labels: duplicate
