### ISSUE TITLE
Incorrect Cache Filenames with Currency Plugin

### ISSUE THREAD

**Issue by CarolineHez** [SatelliteWP/rocket-nginx#156] opened 2021-04-12 18:56 UTC
I'm using WP Rocket (3.8.8) with Nginx (1.18.0), with Rocket-Nginx. I noticed that even in private browsing, I see "x-rocket-nginx-serving-static: No" being sent as a response header.

I get the following debug:

x-rocket-nginx-file: /var/www/html/wp-content/cache/wp-rocket/www.website.com//?v=xxxxxxxxxxxx/index-https.html_gzip
x-rocket-nginx-reason: File not cached
x-rocket-nginx-serving-static: No

I see the file in the folder as:
root@wordpress:/var/www/html/wp-content/cache/wp-rocket/www.website.com/#v=xxxxxxxxxxxx$ ls -l
total 344
-rw-rw-r-- 1 www-data www-data 301833 Apr  9 17:06 index-https-USD.html
-rw-rw-r-- 1 www-data www-data  45183 Apr  9 17:06 index-https-USD.html_gzip

Looks like the one being generated by WP Rocket doesn’t have the “-USD” added to it, causing the serving to fail.

Am using Geolocate (with page caching support) for WooCommerce, together with WooCommerce Currency Converter widget.

Hoping someone is able to point me in the right direction, thanks!

**Comment by maximejobin** [comment] 2021-04-13 13:57
This is a duplicate of #46.

**Closed by maximejobin** 2021-04-13 13:58 UTC
Labels: duplicate

**Comment by CarolineHez** [comment] 2021-04-13 14:01
I'm using this plugin, which is different from the one in #46.

https://woocommerce.com/products/currency-converter-widget/
